Add `SystemStart` and `BootStart` start types
mullvad/windows-service-rs pull request #113
Opened 2023-12-20 19:08 UTC by kkent030315

Added `SystemStart` (`SERVICE_SYSTEM_START`) and `BootStart` (`SERVICE_BOOT_START`) start types.
This change has been tested locally.

2023-12-20 19:40 UTC, pronebird commented
Would be great to document that these two new constants are used for drivers to avoid confusion with a regular `SERVICE_AUTO_START`.

See: https://learn.microsoft.com/en-us/windows/win32/api/winsvc/nf-winsvc-createservicea

2023-12-20 20:07 UTC, kkent030315 commented
> Would be great to document that these two new constants are used for drivers to avoid confusion with a regular `SERVICE_AUTO_START`.
> 
> See: https://learn.microsoft.com/en-us/windows/win32/api/winsvc/nf-winsvc-createservicea

I've added more precise comments on them to avoid confusing with usermode service start types. :+1:

2023-12-21 16:20 UTC, faern requested changes
Sounds like a good change. This will be a breaking change since we add variants to a public enum. I think we should mark this enum as `#[non_exhaustive]` to prevent that in the future.

2023-12-22 00:45 UTC, kkent030315 commented
> Sounds like a good change. This will be a breaking change since we add variants to a public enum. I think we should mark this enum as `#[non_exhaustive]` to prevent that in the future.

@faern Thank you for the review. I've added the `#[non_exhaustive]` attribute for the backwards compatibility (81331bced5f8d2fe4df071cad2409c859303f46d).

2023-12-27 11:36 UTC, dlon approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mullvad/windows-service-rs/113#-:-Nmf2xq62xZtoRPhTyk-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @kkent030315)

___
*[`src/service.rs` line 89 at r3](https://reviewable.io/reviews/mullvad/windows-service-rs/113#-Nmf2Lv1-Onc3kqaoEig:-Nmf2Lv1-Onc3kqaoEih:b9ncvmw) ([raw file](https://github.com/mullvad/windows-service-rs/blob/81331bced5f8d2fe4df071cad2409c859303f46d/src/service.rs#L89)):*
> ```XML
> #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
> #[repr(u32)]
> #[non_exhaustive]
> ```

It looks like this actually is exhaustive now. So maybe this attribute is unnecessary.


<!-- Sent from Reviewable.io -->

2023-12-27 11:53 UTC, kkent030315 commented
@dlon Thank you for the review. I've removed the `#[non_exhaustive]` in d450630322e9c5897855dd10f3040cedffa77a77.

2023-12-27 12:42 UTC, merged