Add `Error.is_os_error`
mullvad/windows-service-rs pull request #89
Opened 2023-02-07 15:40 UTC by citreae535

This function checks if an error from win32 API call matches a specific OS error code. This makes it easier for users to check specific API errors.

2023-02-08 11:09 UTC, pronebird requested changes
Nice addition. A few leftovers in this PR just like in all others.

> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mullvad/windows-service-rs/89#-:-NNkh9cVDBUXBZc37TGT:b-t9mipq)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @citreae535)

___
*[`src/lib.rs` line 272 at r1](https://reviewable.io/reviews/mullvad/windows-service-rs/89#-NNkeHX1EGWSRXbotYJ8:-NNkeHX1EGWSRXbotYJ9:bz4heol) ([raw file](https://github.com/mullvad/windows-service-rs/blob/c4fbc76dce8f2ee53809ea57ba1e13097fe09b14/src/lib.rs#L272)):*
> ```XML
>     /// [official docs]: https://learn.microsoft.com/en-us/windows/win32/api/winsvc/#functions
>     pub fn is_os_error(&self, error_code: i32) -> bool {
>         if let Self::Winapi(e) = self {
> ```

I think historically we prefer to avoid `return`. This could have been written as a match statement instead, i.e:

```rs
match self {
    Self::Winapi(e) => e.raw_os_error() == Some(error_code),
    _ => false
}
```


<!-- Sent from Reviewable.io -->

2023-02-13 08:20 UTC, faern commented
I'm not against this PR. But I also want to note that this crate is supposed to be a high level abstraction for Windows services, and a user of the library should preferably not need to deal with OS error codes or other `windows-sys` stuff if possible.

2023-02-15 12:17 UTC, citreae535 commented
Hmm, I reconsidered it and have to agree that most users won't need this change. Better close it then.

2023-02-15 12:17 UTC, closed without merging

2023-02-15 12:42 UTC, pronebird commented
Currently we do not translate errors returned from syscalls into meaningful errors. Instead we return `Winapi(io::Error)` variant so the one has to parse `io::Error` to find the cause of error. 

We could of course introduce new error types and provide error variants for common error codes but we would almost always have to have a `Other(io::Error)` variant since we do not control Windows API. I am not quite sure that beefing up a single `Error` type would be the way to go, on the other side having dedicated errors types would mean that we'd have to have duplicate error variants like those that we currently have in the `Error` type.

Anyhow, reinventing that would be a big task.